### PR TITLE
Added `verify` scenario

### PR DESCRIPTION
**Pull request by retr0h**
Added a trailing validator scenario functional tests.

### CODE REVIEW

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  docs: commands succeeded
  congratulations :)
```

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  doc: commands succeeded
  congratulations :)
```

**Comment by alop** [comment]
oh cool, hows it supposed to look?

**Comment by retr0h** [comment]
It's just ensuring those scenario roles error the way they should.

**Comment by alop** [comment]
k 👍

**Pull request merged**
