### PR TITLE
Consistent env vars for testinfra's Ansible calls

### PR DESCRIPTION
**Pull request by abrown-sg**
* Leverage the same mechanism we use to set env vars for ansible-playbook for testinfra as well
* Replaces #164

### CODE REVIEW

**Comment by retr0h** [comment]
Does this replace #164 ?

**Comment by abrown-sg** [comment]
@retr0h Yep.

Replaces #164

**Comment by retr0h** [comment]
I'm happy to +1 if it solves @elementalvoid's problem.

**Comment by retr0h** [comment]
👍

**Comment by elementalvoid** [comment]
Thanks guys. I can confirm that this resolves the issue.

**Pull request merged**
