### PR TITLE
[WIP] changes to better wrap molecule

### PR DESCRIPTION
**Pull request by detiber**
Still pretty rough, and I'm working through the test failures still, but this allows me to filter out only errors using stderr and not have ansible-lint failures prevent the rest of the tests from running.

### CODE REVIEW

**Comment by detiber** [comment]
@retr0h wanted to get some feedback on this approach before continuing down the path.

Ideal goal for me is to make the command classes more easily usable from external tooling (I'm building a setuptools command to gather and run molecule tests against multiple subdirectories).

**Comment by retr0h** [comment]
> @retr0h wanted to get some feedback on this approach before continuing down the path.

Thanks @detiber.  I'll let you continue on your work for now.  I'll avoid making any major changes to master, and simply push bug fixes.

**Comment by detiber** [comment]
@retr0h After hacking away at this a bit, I think I would rather try to fold it into the v2 work you are planning, that way the concept can be integral to the API, rather than trying to bolt this on in the current state and having to hack the existing component APIs.

Is there a design doc, or requirements list for the v2 work? Or is the v2 branch the canonical documentation for that work?

**Comment by retr0h** [comment]
@detiber The branch is the canonical documentation for the moment.  We also have issues marked with v2 that I would like to make it in.  Currently the v2 branch on this origin is out of date, have been pushing to my fork.  I will sync this origin with current v2 and update you.

If you have time, I can discuss in IRC the general logic behind the changes.  It's a fairly big forklift.

**Comment by retr0h** [comment]
@detiber Okay, v2 branch pushed.

To converge example scenario:

```
$ cd test/scenarios/docker
$ molecule test
```

Unit tests 

```
$ py.test test/unit
```

Still need to wire in functional tests.  I've just nuked most stuff from the repo, and adding back as I need it.

If you have improvements, feel free to submit PRs.  Smaller patch sets are easier to get through.

**Comment by retr0h** [comment]
@detiber If you are free, please take a look at v2.  I've buttoned it up a bit, and should handle your Docker use case.   The scenarios are currently only setup for Ansible 2.2, but would love your eyes and feedback.

Execute the single and mult-node scenarios:

```
$ cd test/scenarios/docker/
$ molecule test
```

http://molecule.readthedocs.io/en/v2/

**Comment by retr0h** [comment]
Closing this PR since @detiber is working off v2 branch.  @detiber please feel free to comment or reopen if that is no longer the case.

**Pull request closed without merging**
