### PR TITLE
Renamed members

### PR DESCRIPTION
**Pull request by retr0h**
Renamed a couple members.

### CODE REVIEW

**Comment by kireledan** [comment]
Definitely a 👍

**Comment by abrown-sg** [comment]
Looks good. Should we land 287 first and then rebase off that? It touches some of these vars.

**Comment by abrown-sg** [comment]
Ready for a rebase. 👍 from me once that's done.

**Comment by retr0h** [comment]
Closing for now.

**Comment by retr0h** [comment]
Ready for review.

**Pull request merged**
