### PR TITLE
Openstack: Use configured ssh key (#722)

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by retr0h** [comment]
@berendt this fix your issue?

**Comment by berendt** [comment]
@retr0h I wil test this tomorrow.

**Comment by retr0h** [comment]
@berendt Any info on your testing?  I wanted to push out a 1.19.2 before I started working on the 1.20 release.

**Comment by berendt** [comment]
@retr0h Sorry, I was busy. I will try to run the test over the weekend. The code itself looks good to me.

**Comment by retr0h** [comment]
Going for it 🎸

**Pull request merged**
