### PR TITLE
Remove include tasks from driver playbooks

### PR DESCRIPTION
**Pull request by berendt**
* the include task itself is outdated
* the outsourced tasks are only used in a single playbook (create)
* it's easier to keep the playbooks in sync with a single playbook
  without additional files

### CODE REVIEW

**Comment by berendt** [comment]
Does that make sense to you? then I would clean up the test directory.

Then I would move the variables set directly in the playbook into a group_vars file (in it's own PR). This makes the playbook completely static.

**Comment by retr0h** [comment]
Ya, makes sense.  Good idea.  Could you also cleanup the includes in the `https://github.com/metacloud/molecule/tree/master/test/resources/playbooks` directory?

**Comment by berendt** [comment]
@retr0h Did a full sync of the playbooks in test. Please double check them.

**Comment by retr0h** [comment]
Thanks @berendt you rock 🎸

**Pull request merged**
