### PR TITLE
Renamed check to syntax

### PR DESCRIPTION
**Pull request by retr0h**
This is in preparation for implementing dry-run #128.

### CODE REVIEW

**Comment by dhutty** [comment]
LGTM, untested.

**Comment by kireledan** [comment]
For some reason, doing the dry run with the docker hosts attempts a connection over ssh. 
image

Also the dry-run should generate an inventory before executing because it does rely on that. For some reason it seems to be ignoring the connection=docker on the dry run part.

**Comment by conorsch** [comment]
Having some trouble while testing this:

```
molecule test
Traceback (most recent call last):
  File "/home/conor/gits/molecule/venv/bin/molecule", line 10, in <module>
    sys.exit(main())
  File "/home/conor/gits/molecule/venv/local/lib/python2.7/site-packages/molecule/cli.py", line 72, in main
    CLI().main()
  File "/home/conor/gits/molecule/venv/local/lib/python2.7/site-packages/molecule/cli.py", line 68, in main
    sys.exit(c.execute()[0])
  File "/home/conor/gits/molecule/venv/local/lib/python2.7/site-packages/molecule/commands.py", line 527, in execute
    command = getattr(sys.modules[__name__], task.capitalize())
AttributeError: 'module' object has no attribute 'Check-syntax'
```

Here's the full command history leading up to that error. Commands are run in the git repo with this PR branch checked out.

```
virtualenv venv && source venv/bin/activate && pip install -r requirements.txt && python setup.py install
molecule --version # shows "1.6.4.dev3"
molecule init dummyrole
cd dummyrole
molecule test
```

Looks like the changes to `capitalize` and `constantize` could use a bit of refinement.

**Comment by retr0h** [comment]
@conorsch yeah I need to give this PR some love.

Btw we have a sample role in the repo for just this purpose. `tests/demo/molecule/`.

**Comment by retr0h** [comment]
@conorsch I have update the PR to simply rename `check` to `syntax` to make way for the proper check command.  Tests are currently passing.

Mind giving a +1/-1 review?

**Comment by conorsch** [comment]
:-1:

Perhaps I'm missing something, but it appears the dry-run option is missing for me:

```
$ molecule syntax

playbook: playbook.yml
$ molecule check
Usage:
    molecule [-hv] <command> [<args>...]
$ molecule -h
Usage:
    molecule [-hv] <command> [<args>...]

Commands:
    syntax        check playbook syntax
    create        create instances
    converge      create and provision instances
    idempotence   converge and check the output for changes
    test          run a full test cycle: destroy, create, converge, idempotency-check, verify and destroy instances
    verify        create, provision and test instances
    destroy       destroy instances
    status        show status of instances
    list          show available platforms, providers
    login         connects to instance via SSH
    init          creates the directory structure and files for a new Ansible role compatible with molecule

Options:
    -h --help     shows this screen
    -v --version  shows the version
$ molecule --version
1.6.4.dev3
```

This is after destroying and recreating the virtualenv [as described above](https://github.com/metacloud/molecule/pull/228#issuecomment-233096846). Installation and attempted test run were executed under git hash 2a85239ce2611023af24c840175b8b039184337c.

**Comment by retr0h** [comment]
> Perhaps I'm missing something, but it appears the dry-run option is missing for me:

Dry option is not yet implemented.  Simply renamed `check` to `syntax` to make room for the check feature, in a PR to come.

**Comment by abrown-sg** [comment]
Need to update docopt string in cli.py.

**Comment by abrown-sg** [comment]
👍

**Comment by retr0h** [comment]
> Need to update docopt string in cli.py.

?  Isn't it?

**Pull request merged**
