### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by rgreinho**

### CODE REVIEW

**Comment by retr0h** [comment]
Should we pin everything then?

**Comment by kireledan** [comment]
I guess it wouldn't hurt to. Although it seems a bit too much. There isn't anything that relies on a specific version as far as I can tell.

**Comment by rgreinho** [comment]
Well, it's best practice. However, YAPF is changing very frequently, so I am in favor of unpinning that one, as there is no benefit of pinning it if we update it every month.

**Comment by kireledan** [comment]
So maybe pin everything except YAPF ? Would that still be in best practice? I'm not familiar with python packaging best practices.

**Comment by retr0h** [comment]
> Well, it's best practice. However, YAPF is changing very frequently, so I am in favor of unpinning that one, as there is no benefit of pinning it if we update it every month.

YAPF was pinned for a reason that different PRs would have different syntax due to different versions being used to perform the feature.  I prefer to keep it pinned so that we all use the same version.

**Comment by rgreinho** [comment]
@retr0h I'm fine with it, as long as we update it regularly. Their updates always bring more clarity to the code formatting.

**Comment by retr0h** [comment]
Should we remove all the pinning w/ the exception of YAPF then?

**Comment by rgreinho** [comment]
I think we should keep them, and update them once in a while.

**Pull request merged**
