### PR TITLE
Allow partial hostnames with `molecule login`

### PR DESCRIPTION
**Pull request by 0xDEC0DE**
Since users typically hate typing any more than they absolutely
have to, allow them to provide partial hostnames to `molecule login`,
and have it do the right thing.

### CODE REVIEW

**Comment by rgreinho** [comment]
:+1:

**Comment by charlieb00** [comment]
I also think this change is :+1:

**Comment by conorsch** [comment]
Please yes.

**Comment by retr0h** [comment]
:+1:

**Pull request merged**
