### PR TITLE
Ensure raw_env_vars contains string values only

### LINKED ISSUE #658: If raw_env_vars contains a var whose value is not a string, molecule silently fails to execute Ansible
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
2.2.0.0

molecule --version

1.14.1.dev37
```

Sha256 of commit is 8eed3f539f0b30b04d98f8ab418a2a5d55cce01f, molecule --version for source checkout seems to be stuck on 1.14

- Molecule installation method: source

# Desired Behaviour

There is no possible key value pair in the ``ansible: {raw_env_vars: {}}`` section that prevents Ansible from getting executed

# Actual Behaviour (Bug report only)

Except from molecule.yml:

```
  raw_env_vars:
    RETRY_FILES_ENABLED: 0
```

```
molecule --debug syntax; echo $?
--> Checking playbook's syntax...
DEBUG: COMMAND
/usr/bin/ansible-playbook tests/test.yml -vvvv --inventory-file=localhost, --syntax-check --limit=all --timeout=30 --diff
255
```

```
$ /usr/bin/ansible-playbook tests/test.yml -vvvv --inventory-file=localhost, --syntax-check --limit=all --timeout=30 --diff; echo $?
Using $ROLE_DIR/ansible.cfg as config file
Set default localhost to localhost
3 plays in tests/test.yml

playbook: tests/test.yml
0
```
The same happens with ``molecule converge``.

This is especially bad since that one is really hard to debug, because there is no error message at all.

I am not even sure if this is the fault of molecule, because [the doc to sh.pys `_env` arg only mentions it must be a dict, not that all values must be string types](https://amoffat.github.io/sh/sections/special_arguments.html?highlight=_env#env).

### PR DESCRIPTION
**Pull request by alvaroaleman**
Required to not silently break Ansible runs.
Fixes #658

### CODE REVIEW

**Comment by retr0h** [comment]
Can we add an ansible platbook unit test for this?

**Comment by alvaroaleman** [comment]
Added that as a docker scenario.

As a sidenote, the unittests don't work for me because my `ls` is at `/usr/bin/ls` and not at `/bin/ls` as expected: https://github.com/metacloud/molecule/blob/master/test/unit/test_util.py#L213

**Comment by alvaroaleman** [comment]
Please do not merge this right now, because I am currently doing another PR that as a side effect also fixes this issue, making a3b5c78 obsolete.

It will probably do not harm to still keep the testcase in cf36101 thought.

**Comment by alvaroaleman** [comment]
Scratch that, I originally thought #667 would be fixing this issue.

**Comment by retr0h** [comment]
@alvaroaleman Thanks for the contribution.  Will be available in 1.17.2.

**Pull request merged**
