### PR TITLE
Allow using environment variables in molecule.yml

### PR DESCRIPTION
**Pull request by alvaroaleman**
With this pull request it is possible to use environment variables in molecule.yml via the `"${my_var}"` syntax.

This is needed when using molecule via a CI, for example to avoid conflicting Openstack instance names on concurrent builds.

### CODE REVIEW

**Comment by retr0h** [comment]
environment variables can already be set.  See the `raw_env_vars` portion of the [ansible section](http://molecule.readthedocs.io/en/stable-1.17/configuration.html?highlight=env#ansible-section).

**Comment by alvaroaleman** [comment]
Its not about setting environment variables for Ansible. It's about using environment variables in the molecule.yml.

**Comment by retr0h** [comment]
> Its not about setting environment variables for Ansible. It's about using environment variables in the molecule.yml.

Yeah, I realized that after I replied.

**Comment by alvaroaleman** [comment]
Just quick question, are you fine with the idea behind this PR? I'd like to know if there is going to get merged once you have time to review and all implementation related issues are resolved.

**Comment by retr0h** [comment]
Hi @alvaroaleman the I like the idea of it.

I think we should look at the way docker compose tackled this, they seriously put a lot of effort into their [discussion](https://github.com/docker/compose/issues/1377).

I'd like to see us implement their test cases and general method.
https://github.com/docker/compose/pull/1765/files

**Comment by retr0h** [comment]
@alvaroaleman Have a look at #709.  I implemented similar for molecule v2, and used the Docker compose work.

**Comment by alvaroaleman** [comment]
Hey @retroh, can we just cherry pick your work from v2 into v1 and close this PR?

**Comment by retr0h** [comment]
Thanks @alvaroaleman you rock!

**Pull request merged**
