### PR TITLE
Fixed passing flags to molecule test

### LINKED ISSUE #199: Multiple platforms support (--platform option not working)
```
$ molecule --version
1.5.1
```

I would assume that Molecule would run `molecule test` for each platform listed in platforms but that doesn't seem to be the case. Below is my `molecule.yml` file.

```yaml
vagrant:
  raw_config_args:
    - "ssh.insert_key = false"

  platforms:
    - name: trusty64
      box: ubuntu/trusty64
    - name: precise64
      box: ubuntu/precise64

  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 1024
        cpus: 2

  instances:
    - name: s1
      options:
        append_platform_to_hostname: no
```

When running `molecule test`: 

Only `trusty64` platform is tested in Vagrant. I would expect Molecule to run tests for each platform listed in `platforms`.

When running `molecule test --platform=precise64`:

Still trusty64 is being used.... `--platform` option doesn't change behaviour.

```
Bringing machine 's1' up with 'virtualbox' provider...
==> s1: Cloning VM...
==> s1: Matching MAC address for NAT networking...
==> s1: Checking if box 'ubuntu/trusty64' is up to date...
```

### PR DESCRIPTION
**Pull request by abrown-sg**
* Fixes #199

### CODE REVIEW

**Comment by abrown-sg** [comment]
```
molecule test --platform all
--> Destroying instances ...
--> Checking playbooks syntax ...

playbook: playbook.yml

--> Creating instances ...
Bringing machine 'demo-01-ubuntu' up with 'virtualbox' provider...
Bringing machine 'demo-01-centos7' up with 'virtualbox' provider...

--> Starting Ansible Run ...

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [demo-01-centos7]
ok: [demo-01-ubuntu]

TASK: [molecule | Make sure ethtool is installed for our tests] ***************
ok: [demo-01-centos7]
ok: [demo-01-ubuntu]

TASK: [molecule | Make sure ethtool is installed for our tests] ***************
skipping: [demo-01-centos7]
skipping: [demo-01-ubuntu]

TASK: [molecule | Create a file so we can test something with serverspec] *****
changed: [demo-01-ubuntu]
changed: [demo-01-centos7]

TASK: [molecule | Test ability to target ansible tags (molecule1)] ************
ok: [demo-01-centos7]
ok: [demo-01-ubuntu]

TASK: [molecule | Test ability to target ansible tags (molecule2)] ************
ok: [demo-01-ubuntu]
ok: [demo-01-centos7]

PLAY RECAP ********************************************************************
demo-01-centos7            : ok=5    changed=1    unreachable=0    failed=0
demo-01-ubuntu             : ok=5    changed=1    unreachable=0    failed=0

--> Idempotence test in progress (can take a few minutes)...
--> Starting Ansible Run ...
Idempotence test passed.
--> Executing testinfra tests found in tests/.
============================= test session starts ==============================
platform darwin -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
plugins: xdist-1.14, mock-1.1, testinfra-1.4.0
collected 2 itemss

tests/test_default.py ..
=========================== 2 passed in 1.99 seconds ===========================

```

**Comment by retr0h** [comment]
👍

**Comment by alop** [comment]
👍

**Comment by retr0h** [comment]
Cherry picked to stable/1.x branch.  May want to release a 1.8.3 molecule.

**Pull request merged**
