### PR TITLE
Added SUSE docker image support

### PR DESCRIPTION
**Pull request by retr0h**
Fixes: #513

### CODE REVIEW

**Comment by retr0h** [comment]
```
       	Successfully built 48a8f621e6f6
Finished building molecule_local/opensuse:latest
Creating container group-vars-scenario with base image opensuse:latest ...
Container created.
```

**Comment by dj-wasabi** [comment]
@retr0h I do have some issues with testing my role with this fix. So I'm not sure if this is everything that has to be done for making it work with OpenSuse.

**Comment by retr0h** [comment]
@dj-wasabi what issues are you having?  I am able to spin up a suse container with this change.  However, I need to update molecule.yml with a `command`.

**Comment by dj-wasabi** [comment]
@retr0h 
Maybe not related to this change or maybe just my lack of experience/knowledge working with (open)Suse, but I got this error when executing a playbook:

```
- name: "Suse | Install basic repo file"
  zypper_repository: repo="http://download.opensuse.org/repositories/server:monitoring/openSUSE_{{ ansible_distribution_version }}/server:monitoring.repo"
```
And this is the error I get:
```
TASK [ansible-zabbix-agent : Suse | Install basic repo file] *******************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named xml.dom.minidom
fatal: [zabbix-agent-suse]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_8QVxOQ/ansible_module_zypper_repository.py\", line 329, in <module>\n    main()\n  File \"/tmp/ansible_8QVxOQ/ansible_module_zypper_repository.py\", line 311, in main\n    exists, mod, old_repos = repo_exists(module, repodata, overwrite_multiple)\n  File \"/tmp/ansible_8QVxOQ/ansible_module_zypper_repository.py\", line 147, in repo_exists\n    existing_repos = _parse_repos(module)\n  File \"/tmp/ansible_8QVxOQ/ansible_module_zypper_repository.py\", line 106, in _parse_repos\n    from xml.dom.minidom import parseString as parseXML\nImportError: No module named xml.dom.minidom\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by retr0h** [comment]
Hey @dj-wasabi I checked out your [role](https://github.com/dj-wasabi/ansible-zabbix-agent), and this is not a molecule issue.  Was able to get past the `No module named xml.dom.minidom` issue by tweaking a few things.

```
diff --git a/tasks/Suse.yml b/tasks/Suse.yml
index d680d9a..60e7c54 100644
--- a/tasks/Suse.yml
+++ b/tasks/Suse.yml
@@ -1,8 +1,11 @@
 ---
 # Tasks specific for OpenSuse Systems

+- name: "Install zypper repo dependency"
+  zypper: name=python-xml
+
 - name: "Suse | Install basic repo file"
-  zypper_repository: repo="http://download.opensuse.org/repositories/server:monitoring/openSUSE_{{ ansible_distribution_version }}/server:monitoring.repo"
+  zypper_repository: repo="http://download.opensuse.org/repositories/server:monitoring/openSUSE_Leap_{{ ansible_distribution_version }}/server:monitoring.repo"
   when: zabbix_repo == "zabbix"
   become: yes
   tags:
@@ -16,4 +19,4 @@
   become: yes
   tags:
     - zabbix-agent
-    - init
\ No newline at end of file
+    - init
```

**Comment by dj-wasabi** [comment]
@retr0h Thanks! So I was lacking of Suse knowledge. :-)
Then this PR looks good to me. 👍

**Comment by retr0h** [comment]
> @retr0h Thanks! So I was lacking of Suse knowledge. :-)

👍

**Pull request merged**
