### PR TITLE
[Docker Driver] Added install_python flag to allow skipping of python installation

### PR DESCRIPTION
**Pull request by kireledan**
This PR addresses the issue #245 to allow the user to skip the installation of python on a docker image. 
By default, the docker driver will build an image on top of the user specified image with python guaranteed to be installed. If the user passes in the flag ```install_python: no``` into either the docker driver config or container, it will be skipped. 

## Example
To skip the installation for all instances...
``` yaml
---
docker:
  install_python: no
  containers:
    - name: test1
      image: ubuntu
      image_version: latest
```

To skip the installation on only one instance
``` yaml
---
docker:
  containers:
  - name: test1-01
    ansible_groups:
      - group1
    image: ubuntu
    image_version: latest
    install_python: no
  - name: test1-02
    ansible_groups:
      - group2
    image: ubuntu
    image_version: latest

### CODE REVIEW

**Comment by retr0h** [comment]
Can we update the docs

**Comment by kireledan** [comment]
updated.

**Comment by retr0h** [comment]
👍

**Comment by abrown-sg** [comment]
👍

**Comment by kireledan** [comment]
some of the tests borked after rebasing with pytest change - fixing

**Comment by retr0h** [comment]
We should probably remove from [test-requirements](https://github.com/metacloud/molecule/blob/master/test-requirements.txt#L7), yeah?

**Comment by retr0h** [comment]
👍

**Pull request merged**
