### PR TITLE
Add tab completion support

### PR DESCRIPTION
**Pull request by rgreinho**
This patch provides a script to add tab completion support to molecule.
It auto-completes the subcommands, options and dynamic arguments such as
platform, providers, and hosts.

To ease tabular display and porcelain mode, a new
``_display_tabulate_data`` function was implemented in the Molecule
object.

The documentation was updated accordingly.

### CODE REVIEW

**Comment by abrown-sg** [comment]
This looks great! I think you can probably pull PrettyTable from requirements.txt since you removed the only reference to it.

**Comment by rgreinho** [comment]
Reference removed.

**Comment by retr0h** [comment]
> Add tab completion support  …

dang `push -f` :)

**Comment by retr0h** [comment]
👍

**Pull request merged**
