### PR TITLE
Fix #965

### LINKED ISSUE #965: Hardcoded colors
# Issue Type

- Feature request

# Desired Behaviour

When using molecule on a dumb terminal (like emacs one), it should not show the colors code, like this:

`^[[31mERROR: 'molecule/*/molecule.yml' glob failed.  Exiting.^[[0m`

You may find more information on this [nikola issue](https://github.com/getnikola/nikola/issues/2639) I opened some time ago.

### PR DESCRIPTION
**Pull request by drym3r**

### CODE REVIEW

**Comment by drym3r** [comment]
I believe it's better on commit 36d6a5, but then when importing the logger module from the commands, it is not detected as tty, so it won't show colors only on the playbooks. The second commit fixes this, but I'm not sure if it could be a problem on other tty.

PD: Do you know when/if this will be merged and released to pypi? I'm making an emacs wrapper that will need this to work properly (still WIP). FYI https://git.daemons.it/drymer/molecule.el

**Comment by retr0h** [comment]
We will need a unit test for this as I believe this lowers coverage due to the untested branch.

**Comment by retr0h** [comment]
> PD: Do you know when/if this will be merged and released to pypi? I'm making an emacs wrapper that will need this to work properly (still WIP). FYI https://git.daemons.it/drymer/molecule.el

It will get merged once we have unit tests and any outstanding feedback is addressed.

**Comment by drym3r** [comment]
Cool, thanks. It may take some time. I'll try what you suggest on #955.

**Comment by drym3r** [comment]
I'll close this since I don't have time for do the unit tests and because what you sugest worked great. Thanks for your time.

**Pull request closed without merging**
