### PR TITLE
Fixed inventory_file bug

### PR DESCRIPTION
**Pull request by abrown-sg**
* Slightly cleaner and more complete fix to an issue where specifying an inventory file wasn't working
* Molecule sets defaults for inventory_file and config_file that are used unless optionally overridden in ansible config block of molecule.yml.
* Cleaned up error message from previous commit to be consistent with existing style
* Updated docs, tests

### CODE REVIEW

**Comment by abrown-sg** [comment]
yapf 0.6.2 here

**Comment by retr0h** [comment]
> yapf 0.6.2 here

Yeah, same here.  @ephur must have an old version.  We need to figure out how to better ensure our contributors are using the same versions of this library.

**Comment by retr0h** [comment]
:+1:

**Comment by abrown-sg** [comment]
Yeah. The `molecule` section is the default now for the config_file and inventory_file that it writes. Those defaults will be used unless overridden in the `ansible` section now.

**Comment by abrown-sg** [comment]
So now, anything specified in the `ansible` section won't get molecule_dir appended to it. This opens the door for specifying absolute paths. I included config_dir in this change since it would have the same issue inventory_dir did previously.

**Pull request merged**
