### PR TITLE
Add vagrant static network support

### PR DESCRIPTION
**Pull request by TieWei**
This is a fix for https://github.com/metacloud/molecule/issues/155

### CODE REVIEW

**Comment by dhutty** [comment]
Nice. Please update the example in docs/source/usage.rst so that https://molecule.readthedocs.io/en/latest/usage.html#vagrant shows a nic with a static address as well.

**Comment by retr0h** [comment]
👍

**Comment by mcadmin** [comment]
👍

**Comment by delapsley** [comment]
👍

**Pull request merged**
