### PR TITLE
Fix/lint errors

### PR DESCRIPTION
**Pull request by jamatute**
If you run `molecule test` without an `.yamllint` in your role you get the following errors with the docker driver:

```
    /XXX/molecule/default/create.yml
      5:17      warning  truthy value is not quoted  (truthy)
      9:81      error    line too long (87 > 80 characters)  (line-length)
      10:81     error    line too long (85 > 80 characters)  (line-length)
      16:81     error    line too long (116 > 80 characters)  (line-length)
      30:81     error    line too long (92 > 80 characters)  (line-length)
      33:81     error    line too long (124 > 80 characters)  (line-length)
      41:19     warning  truthy value is not quoted  (truthy)
    
    /XXX/molecule/default/prepare.yml
      4:17      warning  truthy value is not quoted  (truthy)
    
    /XXX/molecule/default/destroy.yml
      5:17      warning  truthy value is not quoted  (truthy)
```
I've fixed this warnings and errors for `docker` and `vagrant`

Cheers

### CODE REVIEW

**Comment by retr0h** [comment]
This is somewhat of a moot PR since Molecule will create a `.yamllint` file when creating a new role so a new user should not get these errors.  As part of Molecule's own coding standards these errors are free to be ignored.

However, I see a different issue.  If a user has an existing role and initializes Molecule in an existing role, it appears a `.yamllint` file is not created.  I would be open to a PR to fix that issue.  Feel free to open an issue on that topic and/or submit a PR for it.

Thank you for the interest in Molecule, I hope it's working out for you.

**Comment by jamatute** [comment]
Hi @retr0h, I didn't know that Molecule created the `yamllint` thanks for the tip, I always initialized Molecule inside an already created role.

Nevertheless I would like you to reconsider this PR, even though it doesn't conflict with your coding standards, it does with more strict ones.

I'm forced to respect the 80 lines width limit in my company projects, therefore your `yamllint` doesn't suit me.

So please give it another shot :)

**Comment by alexppg** [comment]
+1

**Comment by sdmorel** [comment]
+1

**Comment by retr0h** [comment]
> I'm forced to respect the 80 lines width limit in my company projects, therefore your yamllint doesn't suit me.
> 
> So please give it another shot :)

You are free to do what you like with the generated files.  if it doesn't fit your standards, you can fix it to fit your standards.

**Comment by retr0h** [comment]
I ended up fixing the truthy rules in #1028.  I may consider long lines.  However, Molecule standards will probably never match the developers standards, so you may need to modify the templates to your own needs.

However, I will look into line length, but thats not something I generally enforce outside .py files.

**Pull request closed without merging**
