### PR TITLE
add docker_host attribute to templates to allow talking to a remote n…

### PR DESCRIPTION
**Pull request by tolland**
add the attribute to support talking to docker over tcp. `molecule.yml` looks like;

```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
    docker_host: 'tcp://localhost:12376'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    DOCKER_HOST: 'tcp://localhost:12376'
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8

```

### CODE REVIEW

**Comment by retr0h** [comment]
@tolland can you update the [test plays](https://github.com/metacloud/molecule/tree/master/test/resources/playbooks/docker) and update the driver [documentation](https://github.com/metacloud/molecule/blob/master/molecule/driver/docker.py).

**Comment by retr0h** [comment]
ping @tolland

**Comment by tolland** [comment]
Ok, will do...

**Comment by retr0h** [comment]
ping @tolland

**Pull request merged**
