### PR TITLE
Added 'all' option to --platform

### LINKED ISSUE #199: Multiple platforms support (--platform option not working)
```
$ molecule --version
1.5.1
```

I would assume that Molecule would run `molecule test` for each platform listed in platforms but that doesn't seem to be the case. Below is my `molecule.yml` file.

```yaml
vagrant:
  raw_config_args:
    - "ssh.insert_key = false"

  platforms:
    - name: trusty64
      box: ubuntu/trusty64
    - name: precise64
      box: ubuntu/precise64

  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 1024
        cpus: 2

  instances:
    - name: s1
      options:
        append_platform_to_hostname: no
```

When running `molecule test`: 

Only `trusty64` platform is tested in Vagrant. I would expect Molecule to run tests for each platform listed in `platforms`.

When running `molecule test --platform=precise64`:

Still trusty64 is being used.... `--platform` option doesn't change behaviour.

```
Bringing machine 's1' up with 'virtualbox' provider...
==> s1: Cloning VM...
==> s1: Matching MAC address for NAT networking...
==> s1: Checking if box 'ubuntu/trusty64' is up to date...
```

### PR DESCRIPTION
**Pull request by kireledan**
This PR allows the user to specify ```--platform all``` to create duplicates of instances with all the platforms listed. This PR resolves #199 in which the expected behavior was that multiple platforms meant multiple instances tested simultaneously.

### CODE REVIEW

**Comment by retr0h** [comment]
👍

**Comment by retr0h** [comment]
Looks good.  @kireledan would you mind adding the following to our demo role?

```
[jodewey:~/git/molecule] [venv] kireledan-multiple_providers(+3/-4)+ 1 ± git diff
diff --git a/tests/demo/molecule/molecule.yml b/tests/demo/molecule/molecule.yml
index a918cb3..078a818 100644
--- a/tests/demo/molecule/molecule.yml
+++ b/tests/demo/molecule/molecule.yml
@@ -1,11 +1,10 @@
 ---
-# ansible:
-#   config_file: ../../.molecule/ansible.cfg
-
 vagrant:
   platforms:
-    - name: ubuntu
+    - name: trusty
       box: ubuntu/trusty64
+    - name: centos7
+      box: centos/7
```

**Comment by retr0h** [comment]
Using the demo role (`tests/demo/molecule`) I encounter a failure on `converge` when using the settings from above.

```
subprocess.CalledProcessError: Command '['/usr/local/bin/vagrant', 'ssh-config', 'demo-01']' returned non-zero exit status 1
```

When adding `append_platform_to_hostname: true` I encounter:

```
subprocess.CalledProcessError: Command '['/usr/local/bin/vagrant', 'ssh-config', 'demo-01-all']' returned non-zero exit status 1
```

**Comment by kireledan** [comment]
Should be all set. Added a check for 'all' in the hostname formatting.

**Comment by retr0h** [comment]
Looks like we have a bug.

Works as expected.  Brings up both platforms.

```
[jodewey:~/git/molecule/tests/demo/molecule] kireledan-multiple_providers(+1/-3)+ ± molecule converge --platform all
Bringing machine 'demo-01-ubuntu' up with 'virtualbox' provider...
Bringing machine 'demo-01-centos7' up with 'virtualbox' provider...
```

Destroying and then running w/o all platforms still brings up all platforms.

```
[jodewey:~/git/molecule/tests/demo/molecule] kireledan-multiple_providers(+1/-3)+ 1 ± molecule destroy
[jodewey:~/git/molecule/tests/demo/molecule] kireledan-multiple_providers(+1/-3)+ ± molecule converge
Bringing machine 'demo-01-ubuntu' up with 'virtualbox' provider...
Bringing machine 'demo-01-centos7' up with 'virtualbox' provider...
```

However, if we remove the .vagrant/ dir, then converge works as expected and only brings up the single platform.  Looks like we have a state file issue.

```
[jodewey:~/git/molecule/tests/demo/molecule] kireledan-multiple_providers(+1/-3)+ ± rm -rf .vagrant
[jodewey:~/git/molecule/tests/demo/molecule] kireledan-multiple_providers(+1/-3)+ ± molecule converge
Bringing machine 'demo-01-ubuntu' up with 'virtualbox' provider...
```

**Comment by retr0h** [comment]
Looks good 👍

**Comment by abrown-sg** [comment]
Looks great! 👍

**Pull request merged**
