### PR TITLE
docker driver 'build_image' added instance specific overrides applciable

### PR DESCRIPTION
**Pull request by j0lly**
Found myself in need of using other containers as dependencies for a given scenarios and I would not create a molecule_local tagged image for a container I just need as dependency, so i gave build_image config option to be overridden by container specific configuration (with priority over driver generic config)

### CODE REVIEW

**Comment by j0lly** [comment]
second push is a bugfix:
did not tested from clean situation (missing molecule_local images).
I think this also deserves a test case and some setup during tests (clean docker host images or such)

**Comment by j0lly** [comment]
Hey @retr0h did u got the chance to look at this PR?

**Comment by retr0h** [comment]
@j0lly needs a rebase.

**Comment by retr0h** [comment]
@kireledan how do you feel about this change?

**Pull request merged**
