### PR TITLE
Use deep merge for config dictionaries

### PR DESCRIPTION
**Pull request by abrown-sg**
* Created new file for "utilities" which will be used more extensively in future changes.

* Switched to using deep dictionary merging for combining config values. Previously, update() would clobber nested settings.

* Tests!

### CODE REVIEW

**Comment by rgreinho** [comment]
@abrown-sg Can you wait before merging please? I wrote a very good deep merge function, but it is more complex than yours and I'd like to compare.

**Comment by rgreinho** [comment]
I might be biased but :+1: :P

**Comment by rgreinho** [comment]
Ah true, it's because the tests come from one of my old projects and I was using ``unittest``.

**Comment by retr0h** [comment]
:+1:

**Pull request merged**
