### PR TITLE
Changed molecule status to display hosts by default.

### PR DESCRIPTION
**Pull request by kireledan**
Currently, if you try running ```molecule status``` you get nothing unless you pass in any flag. It seems more logical to at least display the hosts by default instead of having to pass in anything for that. 

This PR:
* removes ```--hosts``` flag in ```Status```
* Prints the status of hosts by default

### CODE REVIEW

**Comment by rgreinho** [comment]
👎 We need this for the tab completion. If you want to remove it, please provide an alternative.

**Comment by kireledan** [comment]
What should the molecule status command print by default then? It doesn't really make sense that it just prints nothing unless you pass a flag in.

**Comment by rgreinho** [comment]
I see. It does not really bother me, but I would propose this: 
* no arg means "display all", like the ``-a`` arg.
* if (an) arg(s) is/are specified, you display only its/their results.

What do you think?

**Comment by kireledan** [comment]
Yeah. I like that way more. 👍 . I'll change the PR then.

**Comment by rgreinho** [comment]
Fantastic! Thanks.

**Comment by rgreinho** [comment]
``sys.argv < 3`` does no cover all the cases. For instance, ``molecule status --porcelain`` does not display anything.

Instead of using ``sys.argv``, you may want to use the docopt args for this filtering the output of this command:
```
(Pdb) self.args
{'--debug': False,
 '--hosts': False,
 '--platforms': False,
 '--porcelain': False,
 '--providers': False,
 '<command>': 'status'}
```

Also, you must update the tab completion file if you modify the arguments of a command (https://github.com/metacloud/molecule/blob/master/assets/bash_completion/molecule.bash-completion.sh#L37)

**Comment by rgreinho** [comment]
Thank you 👍!

**Pull request merged**
