### PR TITLE
Ansible 2.4 - Update dependencies 

### PR DESCRIPTION
**Pull request by gtirloni**
Our CI builds started failing today after Ansible 2.4 got released

https://github.com/willthames/ansible-lint/issues/278

### CODE REVIEW

**Comment by gtirloni** [comment]
https://github.com/philpep/testinfra/issues/249

**Comment by retr0h** [comment]
Already done in #947.  Released Molecule 2.1 which should pull in newer ansible-lint now.

**Comment by gtirloni** [comment]
@retr0h would you considering releasing 1.26 with this fixed? We're still working on transitioning to 2.x

**Comment by retr0h** [comment]
Sure

**Comment by gtirloni** [comment]
Thank you, much appreciated

**Comment by retr0h** [comment]
Released molecule 1.25.1.

**Pull request merged**
