### PR TITLE
Implemented `check`

### PR DESCRIPTION
**Pull request by retr0h**
The ability to call `molecule check` to perform a "Dry Run".  This is
currently not incorporated into the default test sequence.

Fixes: #128

### CODE REVIEW

**Comment by retr0h** [comment]
Please provide feedback.

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  doc: commands succeeded
  congratulations :)
```

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  doc: commands succeeded
  congratulations :)
```

**Comment by alop** [comment]
this basically does ansible with the 'check' argument, right?

**Comment by alop** [comment]
👍

**Comment by retr0h** [comment]
> this basically does ansible with the 'check' argument, right?

Yeah, and added to the workflow.

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  doc: commands succeeded
  congratulations :)
```

**Comment by geerlingguy** [comment]
Thanks for this, and to anyone finding this in the future, you can add it to your sequence in molecule.yml with:

```yaml
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # Added --check run test.
    - check
    - side_effect
    - verify
    - destroy
```

**Pull request merged**
