### PR TITLE
Broke out verifiers into a directory

### PR DESCRIPTION
**Pull request by retr0h**
We have testinfra/serverspec/rubocop logic scattered across a
couple modules.  This should be self-contained and easy to extend.

### CODE REVIEW

**Comment by retr0h** [comment]
Ran into bugs already fixed by #354 and #352.

```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
ERROR:   py27-ansible19-functional: commands failed
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
ERROR:   py27-ansible21-unit: commands failed
  py27-ansible21-functional: commands succeeded
  docs: commands succeeded
```

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  docs: commands succeeded
  congratulations :)
```

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  docs: commands succeeded
  congratulations :)
```

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  docs: commands succeeded
  congratulations :)
```

**Comment by retr0h** [comment]
```
  syntax: commands succeeded
  py27-ansible19-unit: commands succeeded
  py27-ansible19-functional: commands succeeded
  py27-ansible20-unit: commands succeeded
  py27-ansible20-functional: commands succeeded
  py27-ansible21-unit: commands succeeded
  py27-ansible21-functional: commands succeeded
  docs: commands succeeded
  congratulations :)
```

**Comment by abrown-sg** [comment]
Nice! We're long overdue on this. 👍

**Comment by kireledan** [comment]
Perfect. This will make the goss implementation much smoother too.

**Pull request merged**
