### PR TITLE
Updated Dockerfile template as per #889

### PR DESCRIPTION
**Pull request by aliusmiles**
* Joined multiple RUN statements into one
* Simplified if statements syntax
* Added cache cleaning commands

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
I ran into issues (not 100% related to this PR) when using Ubuntu:16.04 containers and Goss. The "Download and install Goss" stage (a https download) fails because ca-certificates is not installed by default in the container.

Maybe consider adding the respective ca-cert package to the ones installed by default (python, sudo and bash) for each distro.

**Comment by aliusmiles** [comment]
Will look into this.

**Comment by retr0h** [comment]
Also, be sure to update the test docker scenario [Dockerfile](https://github.com/metacloud/molecule/blob/master/test/resources/playbooks/docker/Dockerfile.j2).

**Comment by aliusmiles** [comment]
It appears that ca-certificates are required for ubuntu and apline only.
I've also removed commands for Arch and Gentoo, for the following reasons:
* Building image from _archlinux/base_ fails due to:
```
warning: database file for 'core' does not exist
warning: database file for 'extra' does not exist
warning: database file for 'community' does not exist
error: no operation specified (use -h for help)
```
* Image builds successfully from _base/archlinux_, but converge fails with:
```
 fatal: [arch]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/bin/sh: /usr/bin/python: No such file or directory\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```
`pacman python2` does not create /usr/bin/python symlink, and there seems to be neither systemd neither init-scripts in this image, so it's basically unusable with ansible

* _gentoo/stage3-amd64_ requires volumes_from _gentoo/portage_ or running `emerge-webrsync`, which pulls ~1GB portage tree, and compiling python2 from sources takes quite some time.

I'm frankly not sure how common is testing arch/gentoo in docker, and current RUN commands for those were not working with ansible anyway. Whole idea of Dockerfile in scenario folder is to allow user's customization, right?

**Comment by MarkusTeufelberger** [comment]
For Arch Linux I'd recommend https://hub.docker.com/r/archimg/base/ - seems regularly updated, not extremely large and works with these commands for me. Unfortunately there doesn't seem to be an actual "official" image on dockerhub.

It would still be nice to have the commands for Arch in there by default, other distributions also have /usr/bin/python pointing to Python 3. Which module fails exactly? This seems more like a problem with the failing module than anything else.

**Comment by retr0h** [comment]
@MarkusTeufelberger, yah the Arch commands are in there via subsequent PRs.

**Pull request merged**
