### PR TITLE
CIA-282: Remove hardcoded serverspec dir from rakefile template

### LINKED ISSUE #85: Search in test/integration/default/ for tests
Test-kitchen searches for tests in `test/integration/default/`, see here:
http://kitchen.ci/docs/getting-started/writing-test

It'd be nice if molecule could search there, too, so existing tests do not have to be changed (we test puppet/ansible/chef with the same tests, that reside in the aformentioned directory).

Maybe its also possible to let the user specify where to search for tests?

### PR DESCRIPTION
**Pull request by abrown-sg**
* Fixes #85.
* Passes serverspec_dir through to rakefile template and uses that config value.

### CODE REVIEW

**Comment by rgreinho** [comment]
Question: What if ``serverspec_dir`` is not specified? During the rakefile file generation as the path would start with ``/``. Maybe we should have a default value for it?

**Comment by abrown-sg** [comment]
@rgreinho we set a default in molecule's config. Is that enough?

https://github.com/metacloud/molecule/blob/master/molecule/conf/defaults.yml#L13

**Comment by retr0h** [comment]
> Question: What if serverspec_dir is not specified? During the rakefile file generation as the path would start with /. Maybe we should have a default value for it?

The default is [`spec`](https://github.com/metacloud/molecule/blob/60c55bf5b0bb3d3c44ed7d5f284db96b50a97257/molecule/conf/defaults.yml#L13).  You can override this as @abrown-sg pointed out.

**Comment by retr0h** [comment]
:+1:

**Comment by rgreinho** [comment]
That's perfect :) :+1: too

**Pull request merged**
