### PR TITLE
Feature/add links param to docker

### PR DESCRIPTION
**Pull request by abtreece**
Adds the links parameter which ended up being an easy add. The links functionality is deprecated in Docker though, so the networks parameter is still desireable. This was the "bonus" request in Issue #650

### CODE REVIEW

**Comment by retr0h** [comment]
Hi @abtreece thanks for the PR.  Can you add some tests for this?  See the driver/docker unit tests for reference.

**Comment by abtreece** [comment]
ah, yes... i'll try.

**Comment by abtreece** [comment]
added unit test for links.

**Comment by retr0h** [comment]
Awesome @abtreece.  Thanks a ton!  Will get released to pypi as 1.18 in the next week or so.

**Pull request merged**
