### PR TITLE
Implement sudo password via CLI

### PR DESCRIPTION
**Pull request by retr0h**
Ability to securely collect the sudo password and use it in various
playbooks.

Fixes: #992

### CODE REVIEW

**Comment by retr0h** [comment]
I've added a `--sudo` flag to the base Molecule command (`molecule --sudo`), this will prompt for your sudo password, and make a `MOLECULE_SUDO_PASSWORD` environment available to Molecule.

Now for you to use this, you will need to configure your playbooks which use docker, lxc, whichever as follows.

```
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: False
  become: True
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  vars:
    ansible_sudo_pass: "{{ lookup('env', 'MOLECULE_SUDO_PASSWORD') }}"
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | molecule_from_yaml }}"
  tasks:
```

**Comment by retr0h** [comment]
PR 1000 LOL

~[1000](https://media.giphy.com/media/pBevuxpD4Tq4U/giphy.gif)

**Comment by fujin** [comment]
It's over :nine: :nine: :nine:! Congratulations.

**Comment by msheiny** [comment]
hey @retr0h - this is working great on the `destroy` and `create` but is bombing out on the actual `converge` playbook. Whats the best way I can pass this environment variable to the runner that is calling this playbook? 

```
                       
    TASK [Gathering Facts] *********************************************************                     
    fatal: [gnomeshell_role_f26]: FAILED! => {"failed": true, "msg": "Docker version check (['/usr/bin/docker', 'version', '--format', \"'{{.Server.Version}}'\"]) failed: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.26/version: dial unix /var/run/docker.sock: connect: permission denied\n"}
```

**Comment by retr0h** [comment]
> hey @retr0h - this is working great on the destroy and create but is bombing out on the actual converge playbook. Whats the best way I can pass this environment variable to the runner that is calling this playbook?

You can't just add the inventory var to your playbook.yml as well?

Maybe this is an incomplete solution to the actual problem.

**Comment by msheiny** [comment]
> You can't just add the inventory var to your playbook.yml as well?

No :( Honestly, I think I have to do more research. This is a great start though! I suspect I could be hitting issues with upstream ansible and how they make `docker` connection calls. Maybe I'll need to run ansible as sudo during the converge playbook call ...

**Comment by retr0h** [comment]
Yah, I can just seeing there being all sorts of weird edge cases.  For example if testinfra needs to talk to docker and requires sudo as well, then this solution really wont work.

Can backout to a Molecule on pypi and simply run `sudo molecule test` instead and let the OS prompt you for your sudo password and run molecule itself in privileged mode?

**Comment by msheiny** [comment]
Uggghh totally I can see that cropping up with testinfra and friends. Dang it. Thanks for trying to tackle this. I do really appreciate it and think this is an important issue that needs to get solved but definitely outside the scope of molecule.

I think I'll just use docker-machine to run docker under a VM to solve my woes. However,  I still think this is a valuable PR to leave in. I can't think of any use-case off-hand but I can image a scenario spin-up/spin-down task requires sudo but the rest can be run as regular user. Would just have to add a big disclaimer to the docs.

**Comment by retr0h** [comment]
For shits 'n giggles does `sudo molecule test` work?

**Comment by msheiny** [comment]
errrrr @retr0h - i'll try running that in a disposable VM later, makes me nervous to run the entire molecule environment as root 😬

**Comment by retr0h** [comment]
Closing

**Pull request closed without merging**
